application: dairy1-987 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers: 

- url: /_ah/spi/.*
  script: dairymanagement.api
  secure: always

- url: /js
  static_dir: static/js

- url: /partials
  static_dir: static/partials

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /
  static_files: UserInterface/index.html
  upload: UserInterface/index\.html
  secure: always


libraries:

- name: endpoints
  version: latest

- name: webapp2
  version: latest